Create context_open_in_browser.dart
TarasMazepa/stax pull request #377
Opened 2024-12-28 12:53 UTC by 0xMALVEE

Sub pr of pr creation page
smaller PR one file

2024-12-28 18:56 UTC, TarasMazepa approved these changes

2024-12-28 18:57 UTC, TarasMazepa requested changes
Looking good!
One thing left - as soon as you are extracting code from another code into function, you should replace old code with the call to a new function.

2024-12-29 14:51 UTC, 0xMALVEE commented
> Looking good! One thing left - as soon as you are extracting code from another code into function, you should replace old code with the call to a new function.

boss, this one I didn't understood what to do

2025-01-01 04:52 UTC, TarasMazepa requested changes
Nice! 
As a part of this PR, you need to use this new function in commit command.

2025-01-01 20:12 UTC, TarasMazepa commented on cli/lib/context/context_open_in_browser.dart
> +  void openInBrowser(String url) {
Let's have it return external command, so the user will have control over `announce`, `runSync`, and other options of external commands.
```suggestion
  ExternalCommand openInBrowser(String url) {
```

2025-01-01 20:13 UTC, TarasMazepa commented on cli/lib/context/context_open_in_browser.dart
> +    command(openCommand)
Here let's just have `return` without follow up `announce`, `runSync`, or `printNotEmptyResultFields` 
```suggestion
    return command(openCommand);
```

2025-01-01 20:29 UTC, TarasMazepa commented on cli/lib/context/context_open_in_browser.dart
> +        .announce('Opening URL in browser')
```suggestion
```

2025-01-01 20:30 UTC, TarasMazepa commented on cli/lib/context/context_open_in_browser.dart
> +        .runSync()
```suggestion
```

2025-01-01 20:30 UTC, TarasMazepa commented on cli/lib/context/context_open_in_browser.dart
> +        .printNotEmptyResultFields();
```suggestion
```

2025-01-01 20:30 UTC, TarasMazepa commented on cli/lib/command/internal_command_commit.dart
> +      context.openInBrowser(prUrl);
```suggestion
      context.openInBrowser(prUrl)
          .announce('Opening PR in browser window')
          .runSync()
          .printNotEmptyResultFields();
```

2025-01-01 20:40 UTC, TarasMazepa approved these changes
Looking good!

2025-01-01 20:42 UTC, TarasMazepa commented on cli/lib/command/internal_command_commit.dart
> +      context.openInBrowser(prUrl)
```suggestion
      context
          .openInBrowser(prUrl)
```

2025-01-01 20:46 UTC, merged